    version: '2'
    services:
        web:
            build:
                context: ./
                dockerfile: web.docker
            volumes:
                - ./:/var/www
            ports:
                - "8080:80"
            links:
                - app
            environment:
                DB_PORT: 3306
                DB_HOST: db
        app:
            build:
                context: ./
                dockerfile: app.docker
            volumes:
                - ./:/var/www
            links:
                - db
        db:
            image: mysql
            restart: always
            environment:
                MYSQL_ROOT_PASSWORD: root
                MYSQL_DATABASE: opencart
            ports:
                - "33061:3306"

        adminer:
            image: adminer
            restart: always
            ports:
              - 8081:8080